---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: karpenter-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: karpenter-sa
    namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: karpenter-svc
  namespace: kube-system
  labels:
    app.kubernetes.io/name: karpenter
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http-metrics
  selector:
    app.kubernetes.io/name: karpenter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter
  namespace: kube-system
  labels:
    app.kubernetes.io/name: karpenter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: karpenter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: karpenter
    spec:
      serviceAccountName: karpenter-sa
      containers:
        - name: controller
          command:
            - /karpenter
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          image: localhost:5000/karpenter:latest
          env:
            - name: KWOK_INSTANCE_TYPES_FILE
              value: "/config/instance_types.json"
            - name: KUBERNETES_MIN_VERSION
              value: "1.19.0-0"
            - name: KARPENTER_SERVICE
              value: karpenter
            - name: LOG_LEVEL
              value: "info"
            - name: METRICS_PORT
              value: "8000"
            - name: HEALTH_PROBE_PORT
              value: "8081"
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: controller
                  divisor: "0"
                  resource: limits.memory
            - name: FEATURE_GATES
              value: "Drift=true,SpotToSpotConsolidation=false"
            - name: BATCH_MAX_DURATION
              value: "10s"
            - name: BATCH_IDLE_DURATION
              value: "1s"
          ports:
            - name: http-metrics
              containerPort: 8000
              protocol: TCP
            - name: http
              containerPort: 8081
              protocol: TCP
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          value: ""
